import { AlertTriangle } from "lucide-react";
import LegalPageLayout from "@/components/legal/LegalPageLayout";
import Section from "@/components/legal/Section";

const Disclaimer = () => {
  return (
    <LegalPageLayout title="Medical Disclaimer" icon={AlertTriangle}>
      {/* Important Notice Banner */}
        <div className="rounded-xl bg-primary/5 border border-primary/20 p-5 flex flex-col sm:flex-row gap-4">
          <AlertTriangle className="w-5 h-5 text-primary shrink-0 mt-0.5" aria-hidden="true"/>
          <p className="text-foreground text-sm leading-relaxed">
            <strong>Important:</strong> Symptom Scribe is not a medical device and is not intended to diagnose, treat,
            cure, or prevent any disease or health condition. Always consult a qualified healthcare professional for
            medical advice.
          </p>
        </div>

        <Section title="1. Not Medical Advice">
          <p>
            The content available on <strong className="text-foreground">Symptom Scribe</strong> — including
            AI-generated health insights, symptom analysis, and wellness recommendations — is provided for general
            informational and educational purposes only. It does not constitute medical advice, diagnosis, or treatment.
          </p>
          <p className="mt-3">
            Never disregard professional medical advice or delay in seeking it because of something you have read or
            seen on this platform.
          </p>
        </Section>

        <Section title="2. AI-Generated Content">
          <p>
            The health insights generated by our AI system are based on patterns in publicly available health
            information and the data you provide. These insights:
          </p>
          <ul className="mt-3 space-y-2">
            {[
              "Are not reviewed by licensed medical professionals in real time",
              "May not account for your complete medical history",
              "Should not be used as the sole basis for any health-related decisions",
              "May contain errors or inaccuracies",
            ].map((item) => (
              <li key={item} className="flex items-start gap-2">
                <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-primary shrink-0" />
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </Section>

        <Section title="3. Emergencies">
          <p>
            <strong className="text-foreground">
              If you are experiencing a medical emergency, call your local emergency services immediately (e.g., 112
              or your country's emergency number).
            </strong>{" "}
            Do not rely on Symptom Scribe for emergency medical guidance. The platform is not designed for emergency
            health situations.
          </p>
        </Section>

        <Section title="4. Professional Consultation">
          <p>
            We strongly encourage you to consult with a qualified healthcare provider before making any decisions
            related to your health, treatment, or medication. This is especially important if you have a pre-existing
            medical condition or are currently under medical care.
          </p>
        </Section>

        <Section title="5. No Doctor-Patient Relationship">
          <p>
            Use of Symptom Scribe does not create a doctor-patient relationship between you and Symptom Scribe or any
            of its team members. The platform is a wellness and health tracking tool, not a clinical service.
          </p>
        </Section>

        <Section title="6. Limitation of Liability">
          <p>
            Symptom Scribe shall not be held liable for any health outcomes, decisions, or actions taken based on
            information provided through the platform. Use of the application is at your own risk.
          </p>
        </Section>

        <Section title="7. Contact">
          <p>
            If you have questions about this disclaimer, contact us at{" "}
            <a 
              href="https://github.com/mohdmaazgani/symptom-scribe-clean/issues"
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary hover:underline"
            >
              Open a GitHub Issue
            </a>
            .
          </p>
        </Section>
    </LegalPageLayout>
  );
};

export default Disclaimer;
