// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { browserEnv } from '@/lib/env';
const { supabaseUrl, supabasePublishableKey } = browserEnv;

// ✅ Validate required environment variables
const missingVars = [];
if (!supabaseUrl) missingVars.push('SUPABASE_URL');
if (!supabasePublishableKey) missingVars.push('SUPABASE_PUBLISHABLE_KEY');

if (missingVars.length > 0) {
  throw new Error(
    `Missing required Supabase environment variables:\n` +
    missingVars.map(v => `- ${v}`).join('\n')
  );
}

export const supabase = createClient<Database>(supabaseUrl, supabasePublishableKey, {
  auth: {
    storage: localStorage,
    persistence: 'session',
    autoRefreshToken: true,
  },
});
  
